stages:
  - Test And Build App
  - Release App

image: repo.splunk.com/splunk/infra/phantom_apps_tester:latest

before_script:
  - mkdir -p -m 700 ~/.ssh && echo -e $APP_DEPLOY_KEY > ~/.ssh/app_deploy_key

test:
  stage: Test And Build App
  script: make test
  after_script:
    - make upload
  artifacts:
    name: Test Results
    expire_in: 6 mos
    when: always
    paths: [app_release/results]

build:
  stage: Test And Build App
  script: make build
  image: repo.splunk.com/splunk/infra/phantom_apps_builder:latest
  only:
    - next
    - /^beta\/.+/
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Bumped up the version/
      - $CI_COMMIT_MESSAGE =~ /^\[no-build\]/

release:
  stage: Release App
  script: make release
  only:
    - master
