version: "3.2"

services:
  qa-local:
    image: repo.splunk.com/splunk/infra/phantom_apps_tester:${IMAGE_TAG:-latest}
    environment:
      BUILD_USER_ID: ${USER:-localbuild}
      test_branch: ${TEST_BRANCH:-master}
      WORKSPACE: /build
    volumes:
    - ..:/build
    command: sleep 28800
    secrets:
    - artifactory_token
    - app_deploy_key
    - gitlab_api_token

secrets:
  artifactory_token:
    file: ~/.docker/secrets/artifactory_token
  build_private_key:
    file: ~/.docker/secrets/app_deploy_key
  gitlab_api_token:
    file: ~/.docker/secrets/gitlab_api_token
